// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetProject.Models;

#nullable disable

namespace PetProject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230104063710_updateTeacher")]
    partial class updateTeacher
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PetProject.Model.Model.HomeroomTeacher", b =>
                {
                    b.Property<int>("Id_Htecher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Htecher"), 1L, 1);

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("NameClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Htecher");

                    b.ToTable("HomeroomTeacher");
                });

            modelBuilder.Entity("PetProject.Model.Model.ListClass", b =>
                {
                    b.Property<int>("IdClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClass"), 1L, 1);

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("NameClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClass");

                    b.ToTable("ListClass");
                });

            modelBuilder.Entity("PetProject.Model.Model.ListStudent", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"), 1L, 1);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<int>("IdParent")
                        .HasColumnType("int");

                    b.Property<int>("IdRank")
                        .HasColumnType("int");

                    b.Property<string>("NameStudent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStudent");

                    b.ToTable("ListStudent");
                });

            modelBuilder.Entity("PetProject.Model.Model.ListTeacher", b =>
                {
                    b.Property<int>("IdTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTeacher"), 1L, 1);

                    b.Property<int?>("IdSubject")
                        .HasColumnType("int");

                    b.Property<string>("NameTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdTeacher");

                    b.ToTable("ListTeacher");
                });

            modelBuilder.Entity("PetProject.Model.Model.Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GroundText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Item_Id")
                        .HasColumnType("int");

                    b.Property<int>("Item_Text")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Metadate");
                });

            modelBuilder.Entity("PetProject.Model.Model.Parent", b =>
                {
                    b.Property<int>("IdParent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParent"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("IdParent");

                    b.ToTable("Parent");
                });

            modelBuilder.Entity("PetProject.Model.Model.RankStudent", b =>
                {
                    b.Property<int>("IdRank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRank"), 1L, 1);

                    b.Property<string>("Conduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRank");

                    b.ToTable("RankStudent");
                });

            modelBuilder.Entity("PetProject.Model.Model.Subject", b =>
                {
                    b.Property<int>("IdSubject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubject"), 1L, 1);

                    b.Property<string>("NameSubject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSubject");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("PetProject.Model.Model.SubjectScore", b =>
                {
                    b.Property<int>("IdSubjectScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubjectScore"), 1L, 1);

                    b.Property<int?>("Biology")
                        .HasColumnType("int");

                    b.Property<int?>("Chemistry")
                        .HasColumnType("int");

                    b.Property<int?>("English")
                        .HasColumnType("int");

                    b.Property<int?>("Geography")
                        .HasColumnType("int");

                    b.Property<int?>("History")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<int?>("Literature")
                        .HasColumnType("int");

                    b.Property<int?>("Maths")
                        .HasColumnType("int");

                    b.Property<int?>("PhysicalEducation")
                        .HasColumnType("int");

                    b.Property<int?>("Physics")
                        .HasColumnType("int");

                    b.HasKey("IdSubjectScore");

                    b.ToTable("SubjectScore");
                });

            modelBuilder.Entity("PetProject.Model.Model.TeacherOfClass", b =>
                {
                    b.Property<int>("Id_Htecher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Htecher"), 1L, 1);

                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<int>("IdTeacher")
                        .HasColumnType("int");

                    b.HasKey("Id_Htecher");

                    b.ToTable("TeacherOfClass");
                });
#pragma warning restore 612, 618
        }
    }
}
